# This file was generated by GoReleaser. DO NOT EDIT.
cask "exshell" do
  version "0.0.1"

  on_macos do
    sha256 "e10ad1e1cb02151148394a13479d57f1d1c6b2855735d79969646124ec157f89"
    url "https://github.com/vanlabeke/exshell/releases/download/v#{version}/exshell_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "b7e2f7caf15b4bcac7a68f0474bb6a57f1da9ad230e44de4326066db31c1e69a"
      url "https://github.com/vanlabeke/exshell/releases/download/v#{version}/exshell_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ce313590135888bcc9e18544f7f1e5726ffd0197dbb536732c30caec35d9d09"
      url "https://github.com/vanlabeke/exshell/releases/download/v#{version}/exshell_#{version}_linux_amd64.tar.gz"
    end
  end

  name "exshell"
  desc "Terminal viewer for CSV and XLSX files"
  homepage "https://github.com/vanlabeke/exshell"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exshell"

  # No zap stanza required
end
