# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exshell < Formula
  desc "Terminal viewer for CSV and XLSX files"
  homepage "https://github.com/vanlabeke/exshell"
  version "1.0.0"
  license "BSD-3-Clause"

  on_macos do
    url "https://github.com/vanlabeke/exshell/releases/download/v1.0.0/exshell_1.0.0_darwin_universal.tar.gz"
    sha256 "b60a83090a0b927c1d4a6c8a719a5fed0c4969307e4f91b932882d9d52380500"

    define_method(:install) do
      bin.install "exshell"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v1.0.0/exshell_1.0.0_linux_amd64.tar.gz"
      sha256 "372aa6599ac8ead842bec491bb4bc28597eee573001e39c66223c62d3b121eea"
      define_method(:install) do
        bin.install "exshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v1.0.0/exshell_1.0.0_linux_arm64.tar.gz"
      sha256 "72199dad91f08c2ca6f822588cde055cd66acd1e7204c0de3b068b6625408ac7"
      define_method(:install) do
        bin.install "exshell"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/exshell --version")
  end
end
