# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exshell < Formula
  desc "Terminal viewer for CSV and XLSX files"
  homepage "https://github.com/vanlabeke/exshell"
  version "0.0.1"
  license "BSD-3-Clause"

  on_macos do
    url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_darwin_universal.tar.gz"
    sha256 "10be62f5db01c3a856b4a6d84e1bccd2a1f0dab1276b242713d092b0aa789b93"

    define_method(:install) do
      bin.install "exshell"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_linux_amd64.tar.gz"
      sha256 "d9b140c763a9da4cebd8cf8e2f5d4097f3f01228eed48cf82c0809455e5478a7"
      define_method(:install) do
        bin.install "exshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_linux_arm64.tar.gz"
      sha256 "bcd7d4e7207ff424d84fe0275d70a426cf4e36311926e6725436aea2d27197b2"
      define_method(:install) do
        bin.install "exshell"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/exshell --version")
  end
end
