# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exshell < Formula
  desc "Terminal viewer for CSV and XLSX files"
  homepage "https://github.com/vanlabeke/exshell"
  version "0.0.1"
  license "BSD-3-Clause"

  on_macos do
    url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_darwin_universal.tar.gz"
    sha256 "24bc5b91c594c7c427476110b10ba87017a7d69b78e8dd8c75ad4c1716c20879"

    define_method(:install) do
      bin.install "exshell"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_linux_amd64.tar.gz"
      sha256 "d39e9b1c35b18f531d0873b62512aa650abd423c00ce5a8dd0fa60d62d5ce473"
      define_method(:install) do
        bin.install "exshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanlabeke/exshell/releases/download/v0.0.1/exshell_0.0.1_linux_arm64.tar.gz"
      sha256 "8a4a0c339815661356c18c1996670001c255f9c04f99f6a9f5a06c361c1c3b92"
      define_method(:install) do
        bin.install "exshell"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/exshell --version")
  end
end
